apiVersion: batch/v1
kind: Job
metadata:
  name: load-secrets
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: load-secrets
        image: prefecthq/prefect:3.2.0-python3.10
        command:
        - python
        - -c
        - |
          # Note, this script needs to be manually copied from
          # load_secrets.py to load-secrets.yaml
          from prefect.blocks.system import Secret
          import os
          print("Running load secrets...")
          api_usgs_pat = os.getenv("API_USGS_PAT")
          Secret(value=api_usgs_pat).save(name="api-usgs-pat", overwrite=True)
          print(f"✅ Successfully loaded api-usgs-pat into Prefect Secret block.")
          m3works_aws_access_key_id = os.getenv("M3WORKS_AWS_ACCESS_KEY_ID")
          Secret(value=m3works_aws_access_key_id).save(name="m3works-aws-access-key-id", overwrite=True)
          print(f"✅ Successfully loaded m3works-aws-access-key-id into Prefect Secret block.")
          m3works_aws_secret_access_key = os.getenv("M3WORKS_AWS_SECRET_ACCESS_KEY")
          Secret(value=m3works_aws_secret_access_key).save(name="m3works-aws-secret-access-key", overwrite=True)
          print(f"✅ Successfully loaded m3works-aws-secret-access-key into Prefect Secret block.")
        env:
        - name: PREFECT_API_URL
          value: http://prefect-server:4200/api
        - name: API_USGS_PAT
          valueFrom:
            secretKeyRef:
              name: prefect-workflow-secrets
              key: api-usgs-pat
        - name: M3WORKS_AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: prefect-workflow-secrets
              key: m3works-aws-access-key-id
        - name: M3WORKS_AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: prefect-workflow-secrets
              key: m3works-aws-secret-access-key
      restartPolicy: Never